# Generated by Django 5.1.4 on 2025-01-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='password',
        ),
    ]
